version: 2
# updates:
#  - package-ecosystem: "maven"
#    directory: "/"  # ตำแหน่งที่ตั้งของไฟล์ pom.xml
#    schedule:
#      interval: "daily"  # กำหนดความถี่ในการตรวจสอบ เช่น daily, weekly, monthly
#    open-pull-requests-limit: 10  # กำหนดจำนวน PR ที่เปิดได้พร้อมกัน
#    commit-message:
#      prefix: "[Dependabot]"
