# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"  # ระบุโฟลเดอร์ที่มีไฟล์ pom.xml, "/" หมายถึงโฟลเดอร์รากของโปรเจกต์
    schedule:
      interval: "weekly"  # กำหนดให้ Dependabot ตรวจสอบการอัปเดตทุกสัปดาห์
    open-pull-requests-limit: 5  # จำกัดจำนวน PR ที่ Dependabot จะเปิดพร้อมกัน
