version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "theerapat"
    reviewers:
      - "reviewer1"
      - "reviewer2"
    # ignore:
    #   - dependency-name: "specific-dependency"
    #     versions: ["1.x", "2.x"]
