version: '3.8'
services:
  cups-server:
    container_name: cups-printer-president
    hostname: cups-server
    image: ydkn/cups:latest
    ports:
      - "631:631"
    restart: always
    environment:
      ADMIN_PASSWORD: cupsadmin
    networks:
      - cups-network
    user: root
    command:
      [
        "/bin/sh",
        "-c",
        "chmod -R 777 /usr/share/cups/ppd-new && cupsd -f"
      ]
networks:
  cups-network:
    driver: bridge
