version: '3.8'
services:
  cups-server:
    container_name: cutp-printer-president
    hostname: cups-server
    image: ydkn/cups:latest
    ports:
      - "631:631"
    restart: always
    environment:
      ADMIN_PASSWORD: cupsadmin
    networks:
      - cups-network
    volumes:
      - /usr/share/cups/ppd-new:/usr/share/cups/ppd-new

networks:
  cups-network:
    driver: bridge
