name: Run and Test API

on:
  push:
    branches:
      - main  # สำหรับ api
      - master  # สำหรับ web
  pull_request:
    branches:
      - main
      - master

jobs:
  run-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout API repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and Run Spring Boot API
        run: |
          mvn clean install
          nohup mvn spring-boot:run > /dev/null 2>&1 &


  run-web:
    needs: run-api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Web repository
        uses: actions/checkout@v2
        with:
          repository: Theerapat-dev/PresidentDemo-Web
          path: ./PresidentDemo-Web
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build and Run Web
        run: |
          npm install
          npm start

    
