# .github/workflows/api-ci.yml
name: API CI/CD

on:
  push:
    branches:
      - main

jobs:
  run-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout API repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      
      - name: Build and Run Spring Boot API
        run: |
          mvn clean install
          mvn spring-boot:run &
      
      - name: Wait for API to start
        run: sleep 30

      - name: Check if API is Running
        run: |
          curl --fail http://localhost:8080/actuator/health || exit 1


    
