name: Run and Test API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout API repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and Run Spring Boot API
        run: |
          mvn clean install
          nohup mvn spring-boot:run > /dev/null 2>&1 &

      - name: Wait for API to start
        run: |
          echo "Waiting for API to start..."
          for i in {1..60}; do
            if curl --fail http://localhost:8080/actuator/health > /dev/null 2>&1; then
              echo "API is up!"
              exit 0
            fi
            sleep 10
          done
          echo "API did not start in time."
          exit 1
