name: Run and Test API

on:
  push:
    branches:
      - main  # สำหรับ API
  pull_request:
    branches:
      - main

jobs:
  run-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout API repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and Run Spring Boot API
        run: |
          mvn clean install
          nohup mvn spring-boot:run > /dev/null 2>&1 &
